USE [master]
GO

/****** Object:  Database [AuthorDB]    Script Date: 10/11/2016 4:24:09 PM ******/
CREATE DATABASE [AuthorDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AuthorDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AuthorDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AuthorDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AuthorDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AuthorDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AuthorDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AuthorDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AuthorDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AuthorDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AuthorDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AuthorDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AuthorDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AuthorDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AuthorDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AuthorDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AuthorDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AuthorDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AuthorDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AuthorDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AuthorDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AuthorDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AuthorDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AuthorDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AuthorDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AuthorDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AuthorDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AuthorDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AuthorDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AuthorDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AuthorDB] SET  MULTI_USER 
GO

ALTER DATABASE [AuthorDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AuthorDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AuthorDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AuthorDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AuthorDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AuthorDB] SET  READ_WRITE 
GO

